env:
  browser: true
  es6: true
  "jest/globals": true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins: ["jest"]
rules:
  "indent": ["error", 4]
  'no-cond-assign': 0
  'object-shorthand': [2, 'always']
  'no-const-assign': 2
  'no-class-assign': 2
  'no-this-before-super': 2
  'no-var': 2
  'no-unreachable': 2
  'valid-typeof': 2
  'quote-props': [2, 'as-needed']
  'one-var': [2, 'never']
  'prefer-arrow-callback': 2
  'prefer-const': [2, { destructuring: 'all' }]
  'arrow-spacing': 2
  'no-inner-declarations': 0
  'require-atomic-updates': 'off'
  'jest/no-disabled-tests': 'warn'
  'jest/no-focused-tests': 'error'
  'jest/no-identical-title': 'error'
  'jest/prefer-to-have-length': 'warn'
  'jest/valid-expect': 'error'

